services:
  riddle-squid:
    build: ./riddle-squid
    ports:
      - "${GQL_PORT}:${GQL_PORT}"
    environment:
      - DB_URL=${DB_URL}
      - GQL_PORT=${GQL_PORT}
      - RPC_SEPOLIA_URL=${RPC_SEPOLIA_URL}
    restart: unless-stopped

  hasura:
    build: ./hasura
    ports:
      - "${HASURA_PORT:-8080}:8080"
    environment:
      - HASURA_GRAPHQL_DATABASE_URL=${DB_URL}
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
      - HASURA_GRAPHQL_DEV_MODE=true
      - HASURA_GRAPHQL_ENABLED_LOG_TYPES=startup,http-log,webhook-log,websocket-log,query-log
      - HASURA_PORT=${HASURA_PORT:-8080}
    restart: unless-stopped
